# Generated by Django 4.2.5 on 2023-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pros')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
